### ISSUE TITLE
Ampliar Readme

### ISSUE THREAD

**Issue by vicenlu** [danilly7/maquetacion-bootstrap#1]
El README de tu proyecto podría mejorar si añades más detalles sobre las funcionalidades y las tecnologías que has usado. 

Sería útil que describas brevemente el propósito del proyecto y que incluyas el stack tecnológico del mismo.
Puedes utilizar una plantilla o herramientas como chatgpt para generar estos apartados.

https://github.com/danilly7/S1.2.-Bootstrap-SASS/blob/971e9bea73f71df8ba4d61c587ca1925efb4600c/README.md?plain=1#L1

**Comment by danilly7** [comment]
Modificado.
